version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/user/src/app
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/user/src/app
    ports:
      - 4000:4000
    restart: always